### ISSUE TITLE
TypeError: unknown

### ISSUE THREAD

**Issue by samhavens** [JoeStanton/babel-js-to-jsx#14]
This may be completely my fault, and/or I may be misunderstanding the purpose of this library. I am working on a project where the goal is to "borrow" React components from other sites. I was hoping that this library would allow me to avoid forking React Dev Tools and hacking it. Is the point of this project to turn a bundled es5 script into jsx? Or does it work only on components? Or am I way off?

Anyway, here's the error. I am trying to use it on a large file containing a lot of the logic for airbnb's results page, and it is throwing

``` bash
TypeError: unknown: Property children[0] of JSXElement expected node to be of a type ["JSXText","JSXExpressionContainer","JSXElement"] but instead got "StringLiteral"
```

**Comment by JoeStanton** [comment]
This project turns ES5 React components into their ES6 + JSX equivalents. It's not really designed to reverse-engineer a full JS bundle, although I think you'd get decent mileage out of the existing transforms bar a few issues like the one you're experiencing.

It should work, theoretically. Can you try tracking master instead of the tagged NPM release? I might have fixed the above issue, as it was related to an upstream babel change #12.

Good luck!

**Comment by samhavens** [comment]
Thanks, I will give that a shot! Sorry... how does one track the master branch?

**Comment by JoeStanton** [comment]
Set the version of `babel-js-to-jsx` in `package.json` to `joestanton/babel-js-to-jsx` and `rm -rf node_modules && npm install`

**Comment by samhavens** [comment]
Thank you, I have never had to repoint npm like that. Interesting. I did that and still go the same error; so I tried just getting the snippet of code that I am interesting, now I am getting:

``` bash
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

I assume this is from some piece of obfuscated code referencing a variable that is not defined in the snippet I am using. Thanks for your help and the quick response!
